### ISSUE TITLE
shema_migration use int instead of varchar

### ISSUE THREAD

**Issue by FranckErnewein** [cockroachdb/activerecord-cockroachdb-adapter#168]
I'm using rails 6 and the new cockorach adapter (6.0.0beta2)

When I run `rails db:schema:load` (which is used in many rails tasks like db:migrate or db:setup) I have the following error: 
```
PG::DatatypeMismatch: ERROR:  value type int doesn't match type varchar of column "version"
```

This is due to rails which convert the migration version value in an `Int` and try to insert in a `varchar` column in Postgres.
Postgres seem to be tolerant and finally convert it again in varchar.
But this is not the case with cockroach. 

this commit 
https://github.com/cockroachdb/activerecord-cockroachdb-adapter/commit/5247400892e5ec9df4c837e3399bc1b449121f27#diff-c8c37bcec27b647173b8313d65f1724a297c9792dff5d8aae580443f1d78636d
patched it.

But it was reverted here:
https://github.com/cockroachdb/activerecord-cockroachdb-adapter/commit/2deabbf8847ebb429c45d4490d163b0709bdf248#diff-c8c37bcec27b647173b8313d65f1724a297c9792dff5d8aae580443f1d78636d

I guess we should re-add this patch

**Comment by rafiss** [comment]
@FranckErnewein thanks for this report. Would you be able to provide the full error stack trace?

**Comment by rafiss** [comment]
Correction to initial issue description: I believe this is the revert that might be causing the problem: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/commit/08c5ef7b65edaa9be090345ab874a46890f7a13e

I'm going to investigate why the new `_quote` method no longer seems to be working to resolve the problem.

**Comment by FranckErnewein** [comment]
the stack trace (in case it still help)
```
rails db:schema:load --trace
I, [2021-01-13T16:18:54.718669 #60193]  INFO -- sentry: ** [Raven] Raven 3.1.1 configured not to capture errors: Not configured to send/capture in development or test
** Invoke db:schema:load (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:schema:load
rails aborted!
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  value type int doesn't match type varchar of column "version"
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:1087:in `assume_migrated_upto_version'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:54:in `define'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:46:in `define'
/Users/franck.ernewein/directory/db/schema.rb:13:in `<main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:328:in `load_schema'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:400:in `block (3 levels) in <main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
bin/rails:9:in `<main>'

Caused by:
PG::DatatypeMismatch: ERROR:  value type int doesn't match type varchar of column "version"
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:1087:in `assume_migrated_upto_version'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:54:in `define'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:46:in `define'
/Users/franck.ernewein/directory/db/schema.rb:13:in `<main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:328:in `load_schema'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:400:in `block (3 levels) in <main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/franck.ernewein/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => db:schema:load
```

**Comment by rafiss** [comment]
Thanks @FranckErnewein. Can you also share your code where you create the connection to the database? I'd like to see how the connection is configured.

**Comment by FranckErnewein** [comment]
Actually there is no specific code to create the database, I just use `rails db:create`

**Comment by FranckErnewein** [comment]
I wrote a monkeypatch which override `SchemaStatements.assume_migrated_upto_version` and `SchemaStatements.insert_versions_sql` from ActiveRecord.

I just add single quotes around `version` when rails execute SQL queries:

replace [this line](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1203) by 
```ruby
execute("INSERT INTO #{sm_table} (version) VALUES ('#{quote(version)}')")
```

and [this line](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1643) by
```ruby
"INSERT INTO #{sm_table} (version) VALUES ('#{quote(versions)}');"
```

here is the whole file: 

```ruby
module ActiveRecord
  module ConnectionAdapters
    module SchemaStatements
      include ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements
      def assume_migrated_upto_version(version) 
        unless migrations_paths.nil?
          ActiveSupport::Deprecation.warn(<<~MSG.squish)
            Passing migrations_paths to #assume_migrated_upto_version is deprecated and will be removed in Rails 6.1.
          MSG
        end

        version = version.to_i
        sm_table = quote_table_name(schema_migration.table_name)

        migrated = migration_context.get_all_versions
        versions = migration_context.migrations.map(&:version)

        execute("INSERT INTO #{sm_table} (version) VALUES ('#{quote(version)}')") unless migrated.include?(version)

        inserting = (versions - migrated).select { |v| v < version }
        if inserting.any?
          if (duplicate = inserting.find { |v| inserting.count(v) > 1 })
            raise("Duplicate migration #{duplicate}. Please renumber your migrations to resolve the conflict.")
          end
          execute(insert_versions_sql(inserting))
        end
      end

      def insert_versions_sql(versions)
        sm_table = quote_table_name(schema_migration.table_name)

        if versions.is_a?(Array)
          sql = +"INSERT INTO #{sm_table} (version) VALUES\n"
          sql << versions.map { |v| "('#{quote(v)}')" }.join(",\n")
          sql << ";\n\n"
          sql
        else
          "INSERT INTO #{sm_table} (version) VALUES ('#{quote(versions)}');"
        end
      end
    end
  end
end
```

I hope it helps

**Comment by rafiss** [comment]
@FranckErnewein Thanks for that patch! I will investigate it.

But first, I would still like to receive your configuration. Can you share your `config/database.yml`, or the part of your app that calls `ActiveRecord::Base.establish_connection()`? I would like to see how the connection is configured.

**Comment by FranckErnewein** [comment]
Here is the `database.yml`
It is a little bit tricky because
1. for now, there is feature flag USE_COCKROACH to switch quickly from postgres to cockroach during the migration time
2. this service is connected to 2 different databases

```
directory_default: &directory_default
  <% if ENV['USE_COCKROACH'] == 'true' %>
  adapter: cockroachdb
  url: <%= ENV['COCKROACHDB_URL'] %>
  <% else %>
  url: <%= ENV['DATABASE_URL'] %>
  <% end %>
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  database: directory
  migrations_paths: db/directory/migrate

# This database is owned by customer application, and is only used in readonly by directory.
customer_default: &customer_default
  encoding: unicode
  url: <%= ENV['CUSTOMER_DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  database: customer
  migrations_paths: db/customer/migrate

test:
  primary:
    <<: *directory_default
    database: directory_test
  customer:
    <<: *customer_default
    database: themenuapi_test

development:
  primary:
    <<: *directory_default
  customer:
    <<: *customer_default
    database: themenuapi_development

staging:
  primary:
    <<: *directory_default
  customer:
    <<: *customer_default

sandbox:
  primary:
    <<: *directory_default
  customer:
    <<: *customer_default

production:
  primary:
    <<: *directory_default
  customer:
    <<: *customer_default
 ```

**Comment by AlexLamande** [comment]
hi there 👋 

I've got the same issue with a project that only connects with 1 database.
As Frank and I are working together, I use the same `USE_COCKROACH` flag to switch from postgres to cockroach

Here's my `database.yml` (minus stg and prod ones)

```yml
---
default: &default
  encoding: unicode
  pool: <%= [ ENV['SIDEKIQ_WORKER_THREADS'] || 0, ENV['PUMA_THREADS_PER_WEB_PROCESS'] || 0, 5 ].map(&:to_i).max %>
  timeout: 5000
  <% if ENV['USE_COCKROACH'] == 'true' %>
  adapter: 'cockroach'
  url: <%= ENV['COCKROACHDB_URL'] %>
  <% else %>
  adapter: postgresql
  <% if ENV['DATABASE_HOST'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  <% end %>
  <% if ENV['DATABASE_USER'] %>
  user: <%= ENV['DATABASE_USER'] %>
  <% end %>
  <% if ENV['DATABASE_PASSWORD'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  <% end %>
  <% end %>

development:
  <<: *default
  database: corporate_core_development
  
test:
  <<: *default
  <% if ENV['USE_COCKROACH'] != 'true' %>
  <% if ENV['PG_HOST'] %>
  host: <%= ENV['PG_HOST'] %>
  <% end %>
  <% if ENV['PG_USER'] %>
  user: <%= ENV['PG_USER'] %>
  <% end %>
  <% if ENV['PG_PASSWORD'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  <% end %>
  <% end %>
  database: corporate_core_test
```

Thx a lot

**Comment by rafiss** [comment]
Thanks for providing all this information. Unfortunately, I still cannot reliably reproduce the problem. I did the steps below (and tried adding more migrations after). Sometimes it works, but sometimes I get the same error that you are.

Here's what I did:
```
$ rails --version
Rails 6.0.3.4

$ rails new myapp

$ cd myapp

# edit Gemfile to include:
gem 'pg'
gem 'activerecord-cockroachdb-adapter', '6.0.0beta2'

$ bundle install

# edit config/database.yml to look like:
default: &default
  adapter: cockroachdb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: postgresql://root@localhost:26257?sslmode=disable

development:
  <<: *default
  database: defaultdb

test:
  <<: *default
  database: defaultdbtest

$ rails generate migration CreateProducts name:string part_number:string

$ rails db:migrate RAILS_ENV=development
== 20210120221051 AddPartNumberToProducts: migrating ==========================
-- create_table(:products)
   -> 0.0392s
== 20210120221051 AddPartNumberToProducts: migrated (0.0393s) =================

$ rails db:schema:load RAILS_ENV=development --trace
** Invoke db:schema:load (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:schema:load
```

I am not sure what the issue is, but I'll go ahead and add back that patch

**Comment by rafiss** [comment]
@FranckErnewein @AlexLamande I think I have a better idea of the issue now.

I think it relates to using the `url: ` key in the database config. Can you please share the value of your `COCKROACHDB_URL` environment variable?

The code [in ActiveRecord here](https://github.com/rails/rails/blob/01c9cd6b568f0b6734fe376feb070a9168bdcf49/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L290) will use the URL to determine the connection adapter. So that means if your URL looks like `postgresql://user@host:port` then it will use the `postgresql` adapter. This means it will not add quotes, which would normally happen [here in the CockroachDB adapter](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/df06ec2e0af1f5bf65abbd766b63ec4b4e390347/lib/active_record/connection_adapters/cockroachdb/quoting.rb#L23). As a workaround, you can use a url like `cockroachdb://user@host:port`, or instead of using a url, specify all the settings as described in our [example docs](https://www.cockroachlabs.com/docs/stable/build-a-ruby-app-with-cockroachdb-activerecord.html).

**Comment by FranckErnewein** [comment]
You are quite right ...
sorry and thank you.
I close

**Comment by FranckErnewein** [comment]
@rafiss , there is some documentation where you use `postgres://` instead of `cockroach://` . here for example: [github.com/cockroachdb/docs/blob/master/v20.2/cockroach-demo.md](https://github.com/cockroachdb/docs/blob/master/v20.2/cockroach-demo.md) .
