### ISSUE TITLE
Rails object save with TRSerializationFailure

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#209]
Hello,

I have one more problem with the Database v20.1.8 (I cant update fast, we need some weeks) and the Adapter 6.1.2.

This happen sometimes when we try to save our company (`company.save!`). It is not in an extra transaction.
The name is uniq `validates :company_name, presence: true, uniqueness: true`

Our databases are primary and replicas on three locations.

My problem is, I do not know what this error means and how to fix it on my site.

Maybe the retry from Rails is not working correctly or the data is saved even though the error occurs and Rails try to retry.
I have no idea. And with the version 6.1.2 this happens more often then with the beta version.

<img width="1188" alt="Bildschirmfoto 2021-05-21 um 16 11 40" src="https://user-images.githubusercontent.com/4640423/119151924-1f499c80-ba50-11eb-9f98-ba40a6228934.png">

Sometimes with and sometimes without the PG::InternalError.
```ruby
PG::TRSerializationFailure: ERROR:  restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): meta={id=231f5b64 key=/Table/281/1/"\xd1\a\xb3\xc03\x93@0\xb2\x8e\rL\x94G^\x85"/0 pri=0.03644140 epo=0 ts=1621602354.539717400,1 min=1621602350.007020332,0 seq=27} lock=true stat=PENDING rts=1621602350.007020332,0 wto=false max=1621602350.507020332,0

  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block (2 levels) in execute'
  from activesupport (6.1.3.2) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
  from activesupport (6.1.3.2) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
  from activesupport (6.1.3.2) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `block in execute'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:45:in `execute'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:119:in `commit_db_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:210:in `commit'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:294:in `block in commit_transaction'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:285:in `commit_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:340:in `block in within_new_transaction'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:12:in `within_new_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:302:in `save!'
  from activerecord (6.1.3.2) lib/active_record/suppressor.rb:48:in `save!'
  from app/workers/......_worker.rb:12:in `perform'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:196:in `execute_job'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  from sentry-raven (3.1.2) lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:163:in `block in process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:112:in `local'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:257:in `stats'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:79:in `global'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/logger.rb:11:in `with'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:33:in `prepare'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:162:in `process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:43:in `watchdog'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:52:in `block in safe_thread'
PG::InternalError: ERROR:  there is no transaction in progress

  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block (2 levels) in execute'
  from activesupport (6.1.3.2) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
  from activesupport (6.1.3.2) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
  from activesupport (6.1.3.2) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `block in execute'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
  from activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:45:in `execute'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:124:in `exec_rollback_db_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:378:in `rollback_db_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `rollback_db_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:205:in `rollback'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:302:in `block in rollback_transaction'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:300:in `rollback_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:342:in `rescue in block in within_new_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:339:in `block in within_new_transaction'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:12:in `within_new_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:302:in `save!'
  from activerecord (6.1.3.2) lib/active_record/suppressor.rb:48:in `save!'
  from app/workers/....._worker.rb:12:in `perform'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:196:in `execute_job'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  from sentry-raven (3.1.2) lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:163:in `block in process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:112:in `local'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:257:in `stats'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:79:in `global'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/logger.rb:11:in `with'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:33:in `prepare'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:162:in `process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:43:in `watchdog'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:52:in `block in safe_thread'
ActiveRecord::RecordInvalid: Validation failed: Company name has already been taken
  from activerecord (6.1.3.2) lib/active_record/validations.rb:80:in `raise_validation_error'
  from activerecord (6.1.3.2) lib/active_record/validations.rb:53:in `save!'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:302:in `block in save!'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:20:in `block in within_new_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.1.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:12:in `within_new_transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:20:in `rescue in within_new_transaction'
  from activerecord-cockroachdb-adapter (6.1.2) lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb:11:in `within_new_transaction'
  from activerecord (6.1.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  from activerecord (6.1.3.2) lib/active_record/transactions.rb:302:in `save!'
  from activerecord (6.1.3.2) lib/active_record/suppressor.rb:48:in `save!'
  from app/workers/synchronization/create_company_worker.rb:12:in `perform'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:196:in `execute_job'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  from sentry-raven (3.1.2) lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq (6.2.1) lib/sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:163:in `block in process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:112:in `local'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.3.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.1.3.2) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.2.1) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:257:in `stats'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/job_retry.rb:79:in `global'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.2.1) lib/sidekiq/logger.rb:11:in `with'
  from sidekiq (6.2.1) lib/sidekiq/job_logger.rb:33:in `prepare'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:162:in `process'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.2.1) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:43:in `watchdog'
  from sidekiq (6.2.1) lib/sidekiq/util.rb:52:in `block in safe_thread'
```

**Comment by otan** [comment]
Is this the telemetry code perhaps? cc @keithdoggett

**Comment by otan** [comment]
i'm also seeing this in CI: https://github.com/cockroachdb/cockroach/issues/65297#issuecomment-847733509

looks like transactions which run into `TransactionRetryWithProtoRefreshError` get returned to the pool and are permanently bad

**Comment by keithdoggett** [comment]
I'm a little confused about what's going on with the logs @Piioo. Is this the result of multiple retries from sidekiq or are these the logs from just one call to `Company.save!`?

But yes it seems like something is going on with connections not being able to recover from `TransactionRetryWithProtoRefreshError`s. It looks like there's an attempt to handle `SerializationFailure`s in the transaction_manager currently though:

https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/80c19c10229466db09bda6f6575a5f7877ddf255/lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb#L11-L29

Maybe this doesn't work anymore or we need to add an additional check to this. Any ideas on how to reproduce this error?

**Comment by Piioo** [comment]
@keithdoggett this should be only one call of `company.save!`.
Retries from Sidekiq would ends in a new bug report.

**Comment by otan** [comment]
can you try set `disable_cockroachdb_telemetry` to true in your config @Piioo and see if it persists?

**Comment by Piioo** [comment]
@otan may you explain please more what this will do? I haven't find a good explanation.

**Comment by otan** [comment]
It will disable sending a packet to cockroachdb indicating the active record version.

**Comment by Piioo** [comment]
@otan maybe it helped, but Im not sure. Im still seeing this error, but maybe less.

I hope the Database Update will be done in the near future in our team (hope this will remove all the errors)

**Comment by Piioo** [comment]
It seems to work better with DB version 21.1
