### ISSUE TITLE
PG::FeatureNotSupported: ERROR:  setting IntervalStyle is not enabled

### ISSUE THREAD

**Issue by sirwolfgang** [cockroachdb/activerecord-cockroachdb-adapter#236]
Rails/AR 6.1 seems to have added a new `interval` type, which breaks compatibility. I am unable to do a basic `db:create`

```
Caused by:
PG::FeatureNotSupported: ERROR:  setting IntervalStyle is not enabled
DETAIL:  Setting IntervalStyle changes the volatility of string::interval or interval::string casts from immutable to stable. No computed columns, partial indexes, partitions and check constraints can use this casts. Use to_char_with_style or parse_interval instead if you need these casts to work in the aforementioned cases.
HINT:  You can enable IntervalStyle customization for all sessions with the cluster setting sql.defaults.intervalstyle_enabled, or per session using SET intervalstyle_enabled = true.
```

**Comment by rafiss** [comment]
Thanks for reporting this! This might be a new issue in CockroachDB v21.2. In order for us to best help you, can you provide a few more details:

1. What are your versions of Rails, CockroachDB, and the adapter?
2. When did the problem start? Did you change/upgrade anything?
3. Please provide an example with instructions on how to reproduce the problem.

**Comment by sirwolfgang** [comment]
I created a new Rails project, `v6.1` with the latest version of CoackroachDB `v21.2`, and this adaptor `v6.1.3`. It errored the moment I tried to create my database, with `rails db:create`.

I was able to get around it by downgrading Rails to `v6.0`

**Comment by rafiss** [comment]
Thanks for the information. Support for v21.2 was added in https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/229 which just got merged today. So be on the lookout for the next release, which should hopefully resolve your problem. cc @keithdoggett

**Comment by keithdoggett** [comment]
Yeah, the next release will automatically enable `intervalStyle` and set it to the format ActiveRecord expects.

https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/cb609fd68a78cae173c94c464a57acc46bce7b36/lib/active_record/connection_adapters/cockroachdb_adapter.rb#L258-L261

**Comment by sirwolfgang** [comment]
This looks to still be an issue with:

Rails `v6.1`
Adaptor `v6.1.4`
CoackroachDB `v21.2.3`

```zsh
✘ bundle exec rails db:create
Running via Spring preloader in process 24805
PG::FeatureNotSupported: ERROR:  setting IntervalStyle is not enabled
DETAIL:  Setting IntervalStyle changes the volatility of string::interval or interval::string casts from immutable to stable. No computed columns, partial indexes, partitions and check constraints can use this casts. Use to_char_with_style or parse_interval instead if you need these casts to work in the aforementioned cases.
HINT:  You can enable IntervalStyle customization for all sessions with the cluster setting sql.defaults.intervalstyle.enabled, or per session using SET intervalstyle_enabled = true.
Couldn't create 'fraktel_dev' database. Please check your configuration.
rake aborted!
ActiveRecord::StatementInvalid: PG::FeatureNotSupported: ERROR:  setting IntervalStyle is not enabled
DETAIL:  Setting IntervalStyle changes the volatility of string::interval or interval::string casts from immutable to stable. No computed columns, partial indexes, partitions and check constraints can use this casts. Use to_char_with_style or parse_interval instead if you need these casts to work in the aforementioned cases.
HINT:  You can enable IntervalStyle customization for all sessions with the cluster setting sql.defaults.intervalstyle.enabled, or per session using SET intervalstyle_enabled = true.
/Users/zane/.gem/ruby/3.0.2/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
/Users/zane/.gem/ruby/3.0.2/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block (2 levels) in execute'
/Users/zane/.gem/ruby/3.0.2/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/zane/.gem/ruby/3.0.2/gems/activesupport-6.1.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/zane/.gem/ruby/3.0.2/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/zane/.gem/ruby/3.0.2/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `block in execute'
/Users/zane/.gem/ruby/3.0.2/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
```

**Comment by sirwolfgang** [comment]
Correction, This looks to be an issue if I try to load the connection via URI as the documented `postgres` prefix seems to overwrite the `adaptor` setting. If I adjust to using `cockroachdb://...` it works as expected.
