### ISSUE TITLE
Remove uniq index

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#299]
Hello,

I try to remove a uniq index:
`add_index :foo, :foo_token unique: true`

with 

`remove_index :foo, name: :foo_token`

and I get

```
-- remove_index(:foo, {:name=>:foo_token})
/usr/local/bundle/gems/prometheus_exporter-2.0.8/lib/prometheus_exporter/instrumentation/method_profiler.rb:97:in `exec': PG::DependentObjectsStillExist: ERROR:  index "foo_token" is in use as unique constraint (ActiveRecord::StatementInvalid)
HINT:  use CASCADE if you really want to drop it.

/usr/local/bundle/gems/prometheus_exporter-2.0.8/lib/prometheus_exporter/instrumentation/method_profiler.rb:97:in `exec': ERROR:  index "foo_token" is in use as unique constraint (PG::DependentObjectsStillExist)
HINT:  use CASCADE if you really want to drop it.
```

Problem:

locally it works fine. But I do not see the uniq constraint in the schema.rb. So maybe it works fine locally, because the constraint is missing. But on staging/production not.

**Comment by BuonOmo** [comment]
Here is my attempt of a reproduction:

```ruby
# frozen_string_literal: true
#
# Adapted from https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_migrations.rb

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord"

  gem "activerecord-cockroachdb-adapter"
end

require "activerecord-cockroachdb-adapter"
require "minitest/autorun"
require "logger"

# You might want to change the database name for another one.
ActiveRecord::Base.establish_connection("cockroachdb://root@localhost:26257/defaultdb")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
    t.text :foo_token
  end
end

class Foo < ActiveRecord::Base
end

class AddIndex < ActiveRecord::Migration::Current # or use a specific version via `Migration[number]`
  def change
    reversible do |dir|
      dir.up do
        add_index :foos, :foo_token, unique: true
      end

      dir.down do
        remove_index :foos, :foo_token
      end
    end
  end
end

class BugTest < ActiveSupport::TestCase
  def test_migration
    AddIndex.migrate(:up)
    AddIndex.migrate(:down)
  end
end
```

I don't think there is any issue in the codebase, you just had to either input the correct name or a column rather than using the `name:` option. If that is not the case, could you update this block of code above to match your case ?
